markdown: kramdown
permalink: /:title.html

author: "darkite"
email: g70423199@gmail.com
description: ""
baseurl: ""
url: ""
twitter_username: ""
github_username:  darkite

paginator: 10

sass:
    sass_dir: vendor
